
# all:
# 	cc json.c
# 	echo -n '{"recursion":{"recursion":"recursion"}}' | ./a.out /dev/stdin | cat -e

# all:
# 	cc calculator.c
# 	./a.out


all:
	cc json_1.c
	echo -n '{"recursion":{"recursion":"recursion"}}' | ./a.out /dev/stdin | cat -e